export interface CountryOption {
	value: string;
	label: string;
}

export const RELEVANT_COUNTRIES: CountryOption[] = [
	{ value: 'US', label: 'United States' },
	{ value: 'GB', label: 'United Kingdom' },
	{ value: 'ES', label: 'Spain' },
	{ value: 'MX', label: 'Mexico' },
	{ value: 'AR', label: 'Argentina' },
	{ value: 'BR', label: 'Brazil' },
	{ value: 'CO', label: 'Colombia' },
	{ value: 'CL', label: 'Chile' },
	{ value: 'PE', label: 'Peru' },
	{ value: 'EC', label: 'Ecuador' },
	{ value: 'VE', label: 'Venezuela' },
	{ value: 'UY', label: 'Uruguay' },
	{ value: 'PY', label: 'Paraguay' },
	{ value: 'BO', label: 'Bolivia' },
	{ value: 'DE', label: 'Germany' },
	{ value: 'FR', label: 'France' },
	{ value: 'IT', label: 'Italy' },
	{ value: 'PT', label: 'Portugal' },
	{ value: 'CA', label: 'Canada' },
	{ value: 'AU', label: 'Australia' },
	{ value: 'NZ', label: 'New Zealand' },
	{ value: 'JP', label: 'Japan' },
	{ value: 'KR', label: 'South Korea' },
	{ value: 'CN', label: 'China' },
	{ value: 'IN', label: 'India' },
	{ value: 'RU', label: 'Russia' },
	{ value: 'SE', label: 'Sweden' },
	{ value: 'NO', label: 'Norway' },
	{ value: 'DK', label: 'Denmark' },
	{ value: 'FI', label: 'Finland' },
	{ value: 'NL', label: 'Netherlands' },
	{ value: 'BE', label: 'Belgium' },
	{ value: 'CH', label: 'Switzerland' },
	{ value: 'AT', label: 'Austria' },
	{ value: 'IE', label: 'Ireland' },
	{ value: 'PL', label: 'Poland' },
	{ value: 'CZ', label: 'Czech Republic' },
	{ value: 'HU', label: 'Hungary' },
	{ value: 'RO', label: 'Romania' },
	{ value: 'GR', label: 'Greece' },
	{ value: 'TR', label: 'Turkey' },
	{ value: 'IL', label: 'Israel' },
	{ value: 'ZA', label: 'South Africa' },
	{ value: 'EG', label: 'Egypt' },
	{ value: 'MA', label: 'Morocco' },
	{ value: 'AE', label: 'United Arab Emirates' },
	{ value: 'SG', label: 'Singapore' },
	{ value: 'MY', label: 'Malaysia' },
	{ value: 'TH', label: 'Thailand' },
	{ value: 'ID', label: 'Indonesia' },
	{ value: 'PH', label: 'Philippines' },
];
