export interface LanguageOption {
	value: string;
	label: string;
}

export const LANGUAGES: LanguageOption[] = [
	{ value: 'ES', label: 'Español' },
	{ value: 'EN', label: 'English' },
	{ value: 'FR', label: 'Français' },
	{ value: 'DE', label: 'Deutsch' },
	{ value: 'IT', label: 'Italiano' },
	{ value: 'PT', label: 'Português' },
	{ value: 'RU', label: 'Русский' },
	{ value: 'JA', label: '日本語' },
	{ value: 'KO', label: '한국어' },
	{ value: 'ZH', label: '中文' },
	{ value: 'AR', label: 'العربية' },
	{ value: 'HI', label: 'हिन्दी' },
	{ value: 'BN', label: 'বাংলা' },
	{ value: 'TR', label: 'Türkçe' },
	{ value: 'NL', label: 'Nederlands' },
	{ value: 'PL', label: 'Polski' },
	{ value: 'SV', label: 'Svenska' },
	{ value: 'DA', label: 'Dansk' },
	{ value: 'FI', label: 'Suomi' },
	{ value: 'NO', label: 'Norsk' },
	{ value: 'CS', label: 'Čeština' },
	{ value: 'HU', label: 'Magyar' },
	{ value: 'RO', label: 'Română' },
	{ value: 'BG', label: 'Български' },
	{ value: 'HR', label: 'Hrvatski' },
	{ value: 'SR', label: 'Српски' },
	{ value: 'SK', label: 'Slovenčina' },
	{ value: 'SL', label: 'Slovenščina' },
	{ value: 'ET', label: 'Eesti' },
	{ value: 'LV', label: 'Latviešu' },
	{ value: 'LT', label: 'Lietuvių' },
	{ value: 'EL', label: 'Ελληνικά' },
	{ value: 'HE', label: 'עברית' },
	{ value: 'FA', label: 'فارسی' },
	{ value: 'TH', label: 'ไทย' },
	{ value: 'VI', label: 'Tiếng Việt' },
	{ value: 'ID', label: 'Bahasa Indonesia' },
	{ value: 'MS', label: 'Bahasa Melayu' },
	{ value: 'FIL', label: 'Filipino' },
	{ value: 'UK', label: 'Українська' },
	{ value: 'CA', label: 'Català' },
	{ value: 'EU', label: 'Euskara' },
	{ value: 'GL', label: 'Galego' },
	{ value: 'GA', label: 'Gaeilge' },
	{ value: 'CY', label: 'Cymraeg' },
	{ value: 'IS', label: 'Íslenska' },
	{ value: 'MT', label: 'Malti' },
	{ value: 'SQ', label: 'Shqip' },
	{ value: 'BS', label: 'Bosanski' },
	{ value: 'MK', label: 'Македонски' },
];

export const VOCALS: LanguageOption[] = [
	...LANGUAGES,
	{ value: 'ZXX', label: 'Instrumental' },
];
